apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gustbook-ui
  namespace: gustbook
spec:
  hosts:
  - "kubedemo.kkzonie.com"
  gateways:
  - istio-system/argocd-gateway
  http:
  - match:
    - uri:
        prefix: /guestbook
    route:
    - destination:
        host: guestbook-ui
        port:
          number: 80